### ISSUE TITLE
Latest IE11 version be recognized as Mozilla 5.0

### ISSUE THREAD

**Issue by ReZeroS** [chetan/UASparser#16]
Here the ie 11 provided user-agent `User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`
, and I got the uaName as Mozilla 5.0 instead of IE 11，as my code like the below.

```
uasParser = new UASparser(OnlineUpdater.getVendoredInputStream());
uaName = uasParser.parse(str).getUaName()
```
Is this a bug or is there any way I can add this user-agent manaually？

**Comment by chetan** [comment]
@ReZeroS Hello, did you read the deprecation notice in the README? 

> **NOTE:** As of December 1, 2014, the upstream User Agent database is no longer free and the old update URL is returning *bad data*.
This means that the OnlineUpdater, OnlineUpdateUASparser, and CachingOnlineUpdateUASparser APIs will retrieve an incorrect database and must be disabled immediately. If you were using any of these methods, please update your code as in the example below.
> You may continue to use this library with the bundled UA database, as long as updating is disabled.

What this means for you is that you are probably getting results from a very old user agent database which is unable to identify IE 11. You'll need to look for an alternative option at this point.
